### ISSUE TITLE
Ausência Arquivo

### ISSUE THREAD

**Issue by holiiveira** [4linux/DevOpsLab-HelloWorld#22]
Na aula 07.3 do treinamento DevOps Essentials (Criar uma pipeline devops), tem um arquivo que não consta nesse repositório:

`templates/pipeline.yml`

**Comment by laeldev** [comment]
Segue o código que estava no material, funcionou aqui

```
name: CI - Lint / Tests / Deploy

on: [push]

jobs:

  lint:
    runs-on: ubuntu-20.04
      
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  tests:
    needs: lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Integrations Test
        run: |
          python test.py
  deploy:
    needs: tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: deploy into heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
```
